# Generated by Django 5.0.1 on 2024-01-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=200)),
                ("post_text", models.CharField(max_length=1000)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
